### ISSUE TITLE
searchCorner() searchLine()?

### ISSUE THREAD

**Issue by joanvallve** [IRI-MobileRobotics/laser_scan_utils#10]
While tracking, not always is necessary to process the whole scan but only search a known feature (corner or line) in the new scan. Discuss about this option.

**Comment by joansola** [comment]
@joanvallve , this is somehow the goal of track() in ProcessorTracker. The discussion you propose may start as follows:

At a higher level than track(), there is also the function processKnownFeatures(), which is trying to find in the incoming Capture the Features present in the last Capture, and if found, establish the constraints.

Also, alongside keyFrame creation, we try to discover new Features. This is done by processNewFeatures(), which also look for new Features in the last Capture. If found, we can create new landmarks with them. Then, we have to track() them again into the incoming Capture. Once finished, we group all features (Known and New) and, upon reset(), the set of all Known and New Features in incoming become the set of Known Features in last.

Can you check out ProcessorTracker::process() and see if the functionality therein is OK for your needs? I think that, for Containers, things may be more difficult (because it involves corners and lines as you suggest, that is, an heterogeneous set of Features) and we need to see how we proceed.

**Comment by joanvallve** [comment]
Since I've been checking ProcessorTracker() I propose this issue... I try to explain it better:

> At a higher level than track(), there is also the function processKnownFeatures(), which is trying to find in the incoming Capture the Features present in the last Capture, and if found, establish the constraints.

Even if this is done in `track()` or in `processKnownFeatures()`, the issue stays the same: There is a need for a function in **laserscanutils** that finds some corners/lines without extracting all lines and corners.

**Comment by joansola** [comment]
Ah, uh, in laserScanUtils... OK! I thought I was in Wolf! :-D Yes, OK.

**Comment by joanvallve** [comment]
In the laser case, I think it is not the way to proceed. It is more efficient processing the whole scan one time instead of searching corners in it. Forget about it!
